### ISSUE TITLE
How to set Scoped Dynamic ArrayField's value on change of dropdown?

### ISSUE THREAD

**Issue by sushmitg** [joepuzzo/informed#294]
I have a dropdown with a list of users. Each user's object has a key "availability" which is an array. when I select the user from the dropdown I want the dynamic ArrayField to update the UI accordingly, for example, `user1` has "availability":
```
[
  {
    "fromSlot": "10:00",
    "toSlot": "16:30",
    "fromDay": "MONDAY",
    "toDay": "THURSDAY"
  },
  {
    "fromSlot": "08:00",
    "toSlot": "11:00",
    "fromDay": "FRIDAY",
    "toDay": "FRIDAY"
  },
  {
    "fromSlot": "10:00",
    "toSlot": "12:30",
    "fromDay": "SATURDAY",
    "toDay": "SATURDAY"
  }
]
```

So the form should show 3 rows of 4 input fields.

Similarly when I select `user2` which has "availability":
```
[
  {
    "fromSlot": "12:00",
    "toSlot": "14:00",
    "fromDay": "MONDAY",
    "toDay": "WEDNESDAY"
  }
]
```

Now all previous 3 rows should be replaced with only 1 row with 4 inputs with `user2`'s values from the "availability" array.

But this isn't working. When I select the `user1` from the dropdown the form updates with 3 rows each with 4 inputs but when I change the dropdown from `user1` to  `user2` the form doesn't update and still shows 3 rows each with 4 inputs.

Here's my code
```
const onDoctorSelected = (e) => {
    const doc = doctors.find(({ slug }) => slug === e.target.value);

    if (doc) {
      setInitialValues([]);
      setSelectedDoc(doc);
      setDocSlug(doc.slug);
      setDocData(doc);
      initDrFields(doc);

    }
  };

  const initDrFields = (data) => {
    formApi.current.setValues(data);
    getPaymentModes(data.slug);
    setProfileImg(data.profilePic);
    if (data.appointmentType) {
      setAppointmentTypes(data.appointmentType);
    }
    setSocialMediaInfo(data.socialMedia);
    if (isCurrentRole(AppConstants.ROLE.DOCTOR)) {
      setDocSlug(data.slug);
    }
    
    formApi.current.setInitialValue("availability", availableSum); // <= this is where i am updating the initial value for "availability"
    formApi.current.setValue(
      "appointmentSlotDurationInMillis",
      convertMilisecondToMinute(data.config.appointmentSlotDurationInMillis)
    );
  };

return (
  <Form
        apiRef={formApi}
        onSubmit={handleSubmit}
        initialValues={{
          availability: [
            {
              fromDay: "",
              toDay: "",
              fromSlot: "",
              toSlot: "",
            },
          ],
        }}
      >

     <ArrayField field="availability">
      {({ add, fields }) => (
        <>
          <Box display="flex" justifyContent="flex-end">
            <Button
              variant="contained"
              color="primary"
              className={classes.button}
              startIcon={<AddIcon />}
              onClick={add}
            >
              ADD
            </Button>
          </Box>
          <TableContainer>
            <Table
              aria-label="simple table"
              id="summaryRow"
              className={classes.table}
            >
              <TableHead>
                <TableRow>
                  <TableCell>
                    <strong>Days</strong>
                  </TableCell>
                  <TableCell>
                    <strong>Time Duration</strong>
                  </TableCell>
                  <TableCell></TableCell>
                </TableRow>
              </TableHead>
              <TableBody>
                {console.log('fields', fields)}
                {fields.map(({ field, key, remove }, i) => (
                  <Scope
                    scope={`availability[${i}]`}
                    key={i}
                  >
                    <TableRow key={key}>
                      <TableCell>
                        <Box display="flex">
                          <SelectInput
                            required={true}
                            className={clsx(
                              globalClass.roundWhiteBg,
                              globalClass.inputWidth
                            )}
                            options={weekDays}
                            field={`fromDay`}
                            placeholder="Select Day"
                            label="From"
                            validateOnBlur
                            validateOnChange
                          />
                          <SelectInput
                            required={true}
                            className={clsx(
                              globalClass.roundWhiteBg,
                              globalClass.inputWidth
                            )}
                            options={weekDays}
                            field={`toDay`}
                            placeholder="Select Day"
                            label="To"
                            validateOnBlur
                            validateOnChange
                          />
                        </Box>
                      </TableCell>
                      <TableCell>
                        <Box display="flex">
                          <TextInput
                            className={clsx(
                              globalClass.roundWhiteBg,
                              globalClass.inputWidth
                            )}
                            containerClassName="mr"
                            field={`fromSlot`}
                            label="From Slot"
                            type="time"
                            InputLabelProps={{
                              shrink: true,
                            }}
                            inputProps={{
                              step: 300, // 5 min
                            }}
                            validateOnBlur
                            validateOnChange
                          />
                          <TextInput
                            className={clsx(
                              globalClass.roundWhiteBg,
                              globalClass.inputWidth
                            )}
                            containerClassName="mr"
                            field={`toSlot`}
                            label="To Slot"
                            type="time"
                            InputLabelProps={{
                              shrink: true,
                            }}
                            inputProps={{
                              step: 300, // 5 min
                            }}
                            validateOnBlur
                            validateOnChange
                          />
                        </Box>
                      </TableCell>
                      <TableCell>
                        {i !== 0 && (
                          <Button
                            variant="contained"
                            color="secondary"
                            className={classes.button}
                            startIcon={<DeleteIcon />}
                            onClick={remove}
                          >
                            Remove
                          </Button>
                        )}
                      </TableCell>
                    </TableRow>
                  </Scope>
                ))}
              </TableBody>
            </Table>
          </TableContainer>
        </>
      )}
    </ArrayField>

<Form/>
)
```

**Comment by joepuzzo** [comment]
Try to reset the select inputs when the values change.

**Comment by joepuzzo** [comment]
you can get access to those specific field apis and reset them.

**Comment by sushmitg** [comment]
No, you don't understand. The `fields` from `({ add, fields })`  isn't updating. Means `    formApi.current.setInitialValue("availability", availableSum); // <= this is where i am updating the initial value for "availability"
` this doesn't work the second time. Basically for `user1` the UI should have 3 rows with 4 * 3 = 12 input fields but for `user2` there should be only 1 row with 4 inputs. When I select `user2` the UI doesn't rerender and there's still those 3 rows with input fields with previous values.

**Comment by joepuzzo** [comment]
Yes I understand.. I may need to update the array field hook to allow reseting to initial value after the initial values change 🤔

**Comment by joepuzzo** [comment]
Ok here is what I have done for you... I just pushed out a new version where the `reset` function on the array field will reset to whatever you have the initial values set to!

**Comment by sushmitg** [comment]
Still doesn't work did you mean `resetField` from `formApi.current.resetField()` or just `reset` from `formApi.current.reset()`?
If you don't mind could you please share code.

**Comment by joepuzzo** [comment]
Reset the array field `availability`

**Comment by joepuzzo** [comment]
https://codesandbox.io/s/resetarrayfieldexample-x4iin?file=/src/App.js <<< that has a bunch of examples of things. Specifically changing initial values when you click the "Set new initial values" button
